import type { Metadata } from 'next'
import { SITE_URL, fullName, profile, socialLinks } from '@/src/content/profile'
import { experience } from '@/src/content/experience'
import { allSkills, skillGroups } from '@/src/content/skills'

export const SITE_TITLE = `${fullName} — Software Engineer, Backend & Full-stack`
export const SITE_DESCRIPTION = `${fullName} is a backend and full-stack software engineer in ${profile.location}, building production APIs, commerce systems and integrations with NestJS, Next.js, MySQL and Redis.`

interface PageMetadataInput {
  title?: string
  description: string
  path: string
  image?: { url: string; width?: number; height?: number; alt: string }
  type?: 'website' | 'article' | 'profile'
}

// Generated by src/app/opengraph-image.tsx. Pages that set openGraph replace the parent's object,
// so it is passed explicitly; a segment's own opengraph-image file still takes precedence.
const DEFAULT_OG_IMAGE = { url: '/opengraph-image', width: 1200, height: 630, alt: SITE_TITLE }

// Every page gets its own canonical URL and matching Open Graph/Twitter data.
export const buildMetadata = ({ title, description, path, image = DEFAULT_OG_IMAGE, type = 'website' }: PageMetadataInput): Metadata => {
  const socialTitle = title ? `${title} — ${fullName}` : SITE_TITLE
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      siteName: fullName,
      title: socialTitle,
      description,
      images: [image],
      locale: 'en_US',
    },
    twitter: {
      card: 'summary_large_image',
      title: socialTitle,
      description,
      images: [image.url],
      creator: `@${profile.handle}`,
    },
  }
}

type JsonLdObject = { '@context'?: 'https://schema.org'; '@type': string; [key: string]: unknown }

const currentRole = experience.find((role) => role.end === null)

// Areas of work, listed ahead of individual tools in the Person schema.
const KNOWS_ABOUT_DOMAINS = ['Backend development', 'API design', 'Full-stack development', 'E-commerce systems', 'Third-party integrations', 'Application security']

export const personSchema = (): JsonLdObject => ({
  '@type': 'Person',
  '@id': `${SITE_URL}/#person`,
  name: fullName,
  alternateName: profile.handle,
  url: SITE_URL,
  image: `${SITE_URL}${profile.photo.src}`,
  jobTitle: profile.role,
  email: `mailto:${profile.email}`,
  address: { '@type': 'PostalAddress', addressLocality: 'Lahore', addressCountry: 'PK' },
  ...(currentRole ? { worksFor: { '@type': 'Organization', name: currentRole.company, url: currentRole.url } } : {}),
  alumniOf: { '@type': 'CollegeOrUniversity', name: 'COMSATS University Islamabad' },
  description: profile.headline,
  knowsAbout: [...KNOWS_ABOUT_DOMAINS, ...skillGroups.flatMap(allSkills)],
  sameAs: [
    ...socialLinks.filter((l) => l.platform === 'github' || l.platform === 'linkedin').map((l) => l.url),
    'https://billypentester.medium.com',
    'https://twitter.com/billypentester',
    'https://www.facebook.com/billypentester',
    'https://www.instagram.com/billypentester',
    'https://www.fiverr.com/billypentester',
  ],
})

export const websiteSchema = (): JsonLdObject => ({
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${SITE_URL}/#website`,
  name: fullName,
  url: SITE_URL,
  inLanguage: 'en',
  publisher: { '@id': `${SITE_URL}/#person` },
})

export const profilePageSchema = (): JsonLdObject => ({
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  url: `${SITE_URL}/about-me`,
  mainEntity: personSchema(),
})

export const homeSchema = (): JsonLdObject[] => [
  websiteSchema(),
  { '@context': 'https://schema.org', ...personSchema() },
]

export const breadcrumbSchema = (trail: { name: string; path: string }[]): JsonLdObject => ({
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [{ name: 'Home', path: '/' }, ...trail].map((crumb, index) => ({
    '@type': 'ListItem',
    position: index + 1,
    name: crumb.name,
    item: `${SITE_URL}${crumb.path === '/' ? '' : crumb.path}`,
  })),
})

export const projectSchema = (project: { title: string; summary: string; slug: string; stack: string[] }): JsonLdObject => ({
  '@context': 'https://schema.org',
  '@type': 'CreativeWork',
  name: project.title,
  description: project.summary,
  url: `${SITE_URL}/projects/${project.slug}`,
  keywords: project.stack.join(', '),
  creator: { '@id': `${SITE_URL}/#person` },
})
