export const SERVICE_HEADING = "Services I Offer"
export const WORK_HEADING = "Work I've done"
export const EXPERIENCE_HEADING = "My Experience"
export const CLIENT_HEADING = "Who I've Worked With"
export const EXPERTISE_HEADING = "Expertise I have"
export const EDUCATION_HEADING = "My Education"
export const CONTACT_HEADING = "Get in touch"

export const HERO_STARTER = "Hi, I'm"
export const HERO_HEADING_START = "I design & build simple yet"
export const HERO_HEADING_END = "beautiful websites"
export const HERO_CHAT_START = "Let's have a chat"

export const CONTACT_DESC = "Let's have a chat and I'll help your next idea comes to the real world."
export const CONTACT_FLAVOUR = "Simple friendly talk in never a bad idea ☺️"